# Generated by Django 5.2.5 on 2025-08-29 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diab_encounters', '0001_initial'),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atc', models.CharField(help_text='ATC classification code (e.g., A10BA02 for Metformin)', max_length=20, validators=[django.core.validators.RegexValidator(message='ATC code must follow the format: One letter, two digits, one or two letters, two digits (e.g., A10BA02)', regex='^[A-Z]\\d{2}[A-Z]{1,2}\\d{2}$')])),
                ('name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('QD', 'Once daily'), ('BID', 'Twice daily'), ('TID', 'Three times daily'), ('QID', 'Four times daily'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('Q12H', 'Every 12 hours'), ('PRN', 'As needed'), ('QW', 'Weekly'), ('QM', 'Monthly')], default='QD', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_orders', to='diab_encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_orders', to='patients_core.patient')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['patient', 'start_date'], name='diab_medica_patient_51171f_idx'), models.Index(fields=['patient', 'end_date'], name='diab_medica_patient_3ea499_idx'), models.Index(fields=['atc'], name='diab_medica_atc_d646d0_idx')],
            },
        ),
    ]
