# Generated by Django 5.2.5 on 2025-08-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_encounter_patient'),
        ('gitdm', '0002_doctorprofile_patientprofile_and_more'),
        ('intelligence', '0002_alter_aisummary_patient'),
        ('laboratory', '0002_alter_labresult_patient'),
        ('pharmacy', '0002_alter_medicationorder_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['medical_code'], name='gitdm_docto_medical_74e8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialty'], name='gitdm_docto_special_d52bac_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['created_at'], name='gitdm_patie_created_8e166b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['national_id'], name='gitdm_patie_nationa_57d1f0_idx'),
        ),
    ]
