# Generated by Django 5.2.5 on 2025-09-03 18:35

import gitdm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitdm', '0004_patientprofile_full_name_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='role',
            field=models.CharField(choices=[('GENERAL', 'پزشک عمومی'), ('ENDO', 'متخصص غدد'), ('CARDIO', 'متخصص قلب'), ('OPHTHAL', 'متخصص چشم'), ('ADMIN', 'مدیر سیستم')], default='GENERAL', help_text='نقش پزشک در سیستم', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_code',
            field=models.CharField(blank=True, db_index=True, help_text='کد نظام پزشکی', max_length=32, validators=[gitdm.validators.validate_medical_code]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(blank=True, help_text='تاریخ تولد', null=True, validators=[gitdm.validators.validate_age_range]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='national_id',
            field=models.CharField(blank=True, help_text='کد ملی 10 رقمی', max_length=20, null=True, unique=True, validators=[gitdm.validators.validate_national_id]),
        ),
    ]
