version: 2

# Ignore test files and test patterns
secret_scanning:
  ignored_paths:
    - 'tests/**'
    - '**/test_*.py'
    - '**/*_test.py'
    - '**/tests.py'
    - '**/*_tests.py'
    - '**/conftest.py'
    - '**/fixtures/**'
  
  # Ignore specific patterns that are safe in test contexts
  ignored_matches:
    - name: test_passwords
      match: 'password="test\d+"'
    - name: test_credentials
      match: 'test123|password123|admin123'
    - name: django_test_users
      match: 'create_user\(.*password=.*test.*\)'