# Generated by Django 5.2.5 on 2025-08-29 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('gitdm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitdm.patient'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'occurred_at'], name='encounters__patient_5da0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['created_by', 'created_at'], name='encounters__created_2325cd_idx'),
        ),
    ]
