# Generated by Django 5.2.5 on 2025-09-03 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicaltimeline',
            new_name='timeline_me_patient_dfc19f_idx',
            old_name='timeline_me_patient_b8f2c1_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaltimeline',
            new_name='timeline_me_event_t_3dd9ad_idx',
            old_name='timeline_me_event_t_a9d3e4_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaltimeline',
            new_name='timeline_me_severit_19d185_idx',
            old_name='timeline_me_severit_c5f7b2_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaltimeline',
            new_name='timeline_me_patient_c10947_idx',
            old_name='timeline_me_patient_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='medicaltimeline',
            new_name='timeline_me_content_a8f0d2_idx',
            old_name='timeline_me_content_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='testreminder',
            new_name='timeline_te_patient_463458_idx',
            old_name='timeline_te_patient_5a9c63_idx',
        ),
        migrations.RenameIndex(
            model_name='testreminder',
            new_name='timeline_te_next_du_95e109_idx',
            old_name='timeline_te_next_du_4f8a21_idx',
        ),
        migrations.RenameIndex(
            model_name='testreminder',
            new_name='timeline_te_test_ty_dd6486_idx',
            old_name='timeline_te_test_ty_7c4b89_idx',
        ),
        migrations.RenameIndex(
            model_name='testreminder',
            new_name='timeline_te_priorit_01e364_idx',
            old_name='timeline_te_priorit_f2d1a8_idx',
        ),
        migrations.AlterField(
            model_name='testreminder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
