# Generated by Django 5.2.5 on 2025-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_alter_aisummary_patient'),
        ('intelligence', '0002_anomaly_detection_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisummary',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
