# Generated by Django 5.2.5 on 2025-09-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_alter_aisummary_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patternanalysis',
            options={'verbose_name': 'Pattern Analysis', 'verbose_name_plural': 'Pattern Analyses'},
        ),
        migrations.RenameIndex(
            model_name='anomalydetection',
            new_name='intelligenc_patient_36b79c_idx',
            old_name='intelligenc_patient_8c5e50_idx',
        ),
        migrations.RenameIndex(
            model_name='anomalydetection',
            new_name='intelligenc_anomaly_561778_idx',
            old_name='intelligenc_anomaly_8c5e50_idx',
        ),
        migrations.RenameIndex(
            model_name='anomalydetection',
            new_name='intelligenc_is_ackn_a6f03e_idx',
            old_name='intelligenc_is_ackn_8c5e50_idx',
        ),
        migrations.RenameIndex(
            model_name='anomalydetection',
            new_name='intelligenc_data_ti_d55040_idx',
            old_name='intelligenc_data_ti_8c5e50_idx',
        ),
        migrations.RenameIndex(
            model_name='baselinemetrics',
            new_name='intelligenc_patient_6ed04c_idx',
            old_name='intelligenc_patient_8c5e4e_idx',
        ),
        migrations.RenameIndex(
            model_name='baselinemetrics',
            new_name='intelligenc_last_ca_f07c9b_idx',
            old_name='intelligenc_last_ca_8c5e4e_idx',
        ),
        migrations.RenameIndex(
            model_name='patternalert',
            new_name='intelligenc_patient_4254a3_idx',
            old_name='intelligenc_patient_8c5e51_idx',
        ),
        migrations.RenameIndex(
            model_name='patternalert',
            new_name='intelligenc_alert_t_5deaaa_idx',
            old_name='intelligenc_alert_t_8c5e51_idx',
        ),
        migrations.RenameIndex(
            model_name='patternalert',
            new_name='intelligenc_created_006433_idx',
            old_name='intelligenc_created_8c5e51_idx',
        ),
        migrations.RenameIndex(
            model_name='patternalert',
            new_name='intelligenc_is_reso_3cd92c_idx',
            old_name='intelligenc_is_reso_8c5e51_idx',
        ),
        migrations.RenameIndex(
            model_name='patternanalysis',
            new_name='intelligenc_patient_3cdae7_idx',
            old_name='intelligenc_patient_8c5e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='patternanalysis',
            new_name='intelligenc_created_295c39_idx',
            old_name='intelligenc_created_8c5e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='patternanalysis',
            new_name='intelligenc_trend_d_bac9e1_idx',
            old_name='intelligenc_trend_d_8c5e4f_idx',
        ),
    ]
