# Generated by Django 5.2.5 on 2025-08-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diab_encounters', '0001_initial'),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc', models.CharField(max_length=40)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=16)),
                ('taken_at', models.DateTimeField()),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diab_encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_core.patient')),
            ],
        ),
    ]
