# Generated by Django 5.2.5 on 2025-08-28 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diab_encounters', '0001_initial'),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loinc', models.CharField(max_length=40)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=16)),
                ('taken_at', models.DateTimeField()),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diab_encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_core.patient')),
            ],
        ),
    ]
