# Generated by Django 5.2.5 on 2025-09-03 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitdm', '0005_doctorprofile_role_alter_doctorprofile_medical_code_and_more'),
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='completed_requires_timestamp',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='reminders_r_patient_67b287_idx',
            old_name='reminders_r_patient_65b5f9_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='reminders_r_due_at_b7eb79_idx',
            old_name='reminders_r_due_at_c9dbff_idx',
        ),
        migrations.RenameIndex(
            model_name='reminder',
            new_name='reminders_r_reminde_c61630_idx',
            old_name='reminders_r_reminde_88f226_idx',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_basic_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='completed_requires_timestamp'),
        ),
    ]
