# Generated by Django 5.2.5 on 2025-09-03 18:35

import gitdm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_medicationorder_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationorder',
            name='dose',
            field=models.CharField(help_text='دوز دارو (مثال: 500mg, 1.5g, 10units)', max_length=50, validators=[gitdm.validators.validate_medication_dose]),
        ),
    ]
