# Generated by Django 5.2.5 on 2025-09-03 18:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('gitdm', '0005_doctorprofile_role_alter_doctorprofile_medical_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('patient_summary', 'خلاصه بیمار'), ('doctor_performance', 'عملکرد پزشک'), ('system_overview', 'نمای کلی سیستم'), ('custom', 'سفارشی')], max_length=20, verbose_name='نوع گزارش')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='فرمت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر فایل')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctoranalytics',
            options={'ordering': ['-date'], 'verbose_name': 'آمار پزشک', 'verbose_name_plural': 'آمارهای پزشکان'},
        ),
        migrations.AlterModelOptions(
            name='patientanalytics',
            options={'ordering': ['-date'], 'verbose_name': 'آمار بیمار', 'verbose_name_plural': 'آمارهای بیماران'},
        ),
        migrations.AlterModelOptions(
            name='systemanalytics',
            options={'ordering': ['-date'], 'verbose_name': 'آمار سیستم', 'verbose_name_plural': 'آمارهای سیستم'},
        ),
        migrations.AddField(
            model_name='doctoranalytics',
            name='avg_encounters_per_patient',
            field=models.FloatField(blank=True, null=True, verbose_name='میانگین ویزیت به ازای هر بیمار'),
        ),
        migrations.AddField(
            model_name='doctoranalytics',
            name='critical_alerts',
            field=models.IntegerField(default=0, verbose_name='هشدارهای بحرانی'),
        ),
        migrations.AddField(
            model_name='doctoranalytics',
            name='new_patients',
            field=models.IntegerField(default=0, verbose_name='بیماران جدید'),
        ),
        migrations.AddField(
            model_name='doctoranalytics',
            name='total_alerts',
            field=models.IntegerField(default=0, verbose_name='کل هشدارها'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='avg_diastolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='میانگین فشار دیاستولیک'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='avg_systolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='میانگین فشار سیستولیک'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='compliance_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز پایبندی به درمان'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='glucose_std_dev',
            field=models.FloatField(blank=True, null=True, verbose_name='انحراف معیار قند خون'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='glucose_trend',
            field=models.CharField(choices=[('improving', 'در حال بهبود'), ('stable', 'ثابت'), ('worsening', 'در حال بدتر شدن')], default='stable', max_length=20, verbose_name='روند قند خون'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='hba1c_trend',
            field=models.CharField(choices=[('improving', 'در حال بهبود'), ('stable', 'ثابت'), ('worsening', 'در حال بدتر شدن')], default='stable', max_length=20, verbose_name='روند HbA1c'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='max_glucose',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(800)], verbose_name='حداکثر قند خون'),
        ),
        migrations.AddField(
            model_name='patientanalytics',
            name='min_glucose',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(800)], verbose_name='حداقل قند خون'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='active_patients',
            field=models.IntegerField(default=0, verbose_name='بیماران فعال'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='avg_patient_hba1c',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(18)], verbose_name='میانگین HbA1c بیماران'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='gitdm.doctorprofile', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='patients_above_goal',
            field=models.IntegerField(default=0, verbose_name='بیماران بالای محدوده هدف'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='patients_at_goal',
            field=models.IntegerField(default=0, verbose_name='بیماران در محدوده هدف'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='performance_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز عملکرد'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='total_encounters',
            field=models.IntegerField(default=0, verbose_name='کل ویزیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='doctoranalytics',
            name='total_patients',
            field=models.IntegerField(default=0, verbose_name='کل بیماران'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='alerts_count',
            field=models.IntegerField(default=0, verbose_name='تعداد هشدارها'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='avg_glucose',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(800)], verbose_name='میانگین قند خون'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='avg_hba1c',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(18)], verbose_name='میانگین HbA1c'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='encounters_count',
            field=models.IntegerField(default=0, verbose_name='تعداد ویزیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='lab_tests_count',
            field=models.IntegerField(default=0, verbose_name='تعداد آزمایش\u200cها'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='medications_count',
            field=models.IntegerField(default=0, verbose_name='تعداد داروها'),
        ),
        migrations.AlterField(
            model_name='patientanalytics',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='gitdm.patientprofile', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='active_users',
            field=models.IntegerField(default=0, verbose_name='کاربران فعال'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='api_calls',
            field=models.IntegerField(default=0, verbose_name='تعداد فراخوانی API'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='avg_system_hba1c',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(18)], verbose_name='میانگین HbA1c سیستم'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='daily_active_users',
            field=models.IntegerField(default=0, verbose_name='کاربران فعال روزانه'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='system_goal_achievement',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد دستیابی به اهداف'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='total_alerts',
            field=models.IntegerField(default=0, verbose_name='کل هشدارها'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='total_doctors',
            field=models.IntegerField(default=0, verbose_name='کل پزشکان'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='total_encounters',
            field=models.IntegerField(default=0, verbose_name='کل ویزیت\u200cها'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='total_lab_tests',
            field=models.IntegerField(default=0, verbose_name='کل آزمایش\u200cها'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='total_medications',
            field=models.IntegerField(default=0, verbose_name='کل نسخه\u200cها'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='total_patients',
            field=models.IntegerField(default=0, verbose_name='کل بیماران'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='total_users',
            field=models.IntegerField(default=0, verbose_name='کل کاربران'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoranalytics',
            unique_together={('doctor', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='patientanalytics',
            unique_together={('patient', 'date')},
        ),
        migrations.AddIndex(
            model_name='doctoranalytics',
            index=models.Index(fields=['doctor', '-date'], name='analytics_d_doctor__9531c4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoranalytics',
            index=models.Index(fields=['date'], name='analytics_d_date_9b6eba_idx'),
        ),
        migrations.AddIndex(
            model_name='patientanalytics',
            index=models.Index(fields=['patient', '-date'], name='analytics_p_patient_2c90b1_idx'),
        ),
        migrations.AddIndex(
            model_name='patientanalytics',
            index=models.Index(fields=['date'], name='analytics_p_date_8c2cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='systemanalytics',
            index=models.Index(fields=['-date'], name='analytics_s_date_a469e1_idx'),
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='gitdm.doctorprofile', verbose_name='پزشک'),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='gitdm.patientprofile', verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='report',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reports', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='analytics_r_status_0c5134_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['requested_by', '-created_at'], name='analytics_r_request_82b676_idx'),
        ),
    ]
