# Generated by Django 5.2.5 on 2025-08-29 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('url', models.URLField(blank=True)),
                ('topic', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['-year', 'title'],
                'indexes': [models.Index(fields=['source'], name='clinical_re_source_c7ed70_idx'), models.Index(fields=['year'], name='clinical_re_year_7a3a7a_idx'), models.Index(fields=['topic'], name='clinical_re_topic_c7caf1_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'source', 'year'), name='uniq_clinref_title_source_year')],
            },
        ),
    ]
