# Generated by Django migration creator on 2025-08-29 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(validators=[])),
                ('url', models.URLField(blank=True)),
                ('topic', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['-year', 'title'],
                'indexes': ["models.Index(fields=['source'], name='clinical_re_source_4d5e6f_idx')", "models.Index(fields=['year'], name='clinical_re_year_7a8b9c_idx')", "models.Index(fields=['topic'], name='clinical_re_topic_1d2e3f_idx')"],
            },
        ),
    ]
