# Generated by Django 5.1.4 on 2024-12-17 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True)),
                ('topic', models.CharField(max_length=80)),
            ],
        ),
    ]