# Generated by Django migration creator on 2025-08-29 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=48)),
                ('resource_id', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('prev_version', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot', models.JSONField()),
                ('diff', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('resource_type', 'resource_id', 'version')},
                'indexes': ["models.Index(fields=['resource_type', 'resource_id', 'version'], name='records_ver_resourc_8f9a0b_idx')", "models.Index(fields=['changed_at'], name='records_ver_changed_2c3d4e_idx')"],
            },
        ),
    ]
