# Generated by Django 5.1.4 on 2024-12-17 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=48)),
                ('resource_id', models.UUIDField()),
                ('version', models.PositiveIntegerField()),
                ('prev_version', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot', models.JSONField()),
                ('diff', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=['resource_type', 'resource_id', 'version'],
                        name='recordver_unique_triplet',
                    ),
                ],
                'indexes': [
                    models.Index(
                        fields=['resource_type', 'resource_id', '-version'],
                        name='recordver_type_id_ver_desc_idx',
                    ),
                ],
            },
        ),
    ]