# Generated by Django 5.2.5 on 2025-08-29 10:52

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_versioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recordversion',
            name='recordver_unique_triplet',
        ),
        migrations.RemoveConstraint(
            model_name='recordversion',
            name='recordver_version_gte_1',
        ),
        migrations.RemoveConstraint(
            model_name='recordversion',
            name='recordver_prev_lt_version',
        ),
        migrations.AlterField(
            model_name='recordversion',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='recordversion',
            unique_together={('resource_type', 'resource_id', 'version')},
        ),
        migrations.AddIndex(
            model_name='recordversion',
            index=models.Index(fields=['resource_type', 'resource_id', 'version'], name='records_ver_resourc_830d74_idx'),
        ),
        migrations.AddIndex(
            model_name='recordversion',
            index=models.Index(fields=['changed_at'], name='records_ver_changed_97dfb3_idx'),
        ),
    ]
