# Generated by Django 5.2.5 on 2025-08-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_auditlog_user_id'),
    ]

    operations = [
    ]
