# Generated by Django 5.2.5 on 2025-09-03 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_role_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'ورود ناموفق'), ('SUSPICIOUS', 'فعالیت مشکوک'), ('UNAUTHORIZED', 'دسترسی غیرمجاز'), ('BREACH_ATTEMPT', 'تلاش نقض داده'), ('BULK_EXPORT', 'خروجی\u200cگیری انبوه')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('LOW', 'پایین'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا'), ('CRITICAL', 'بحرانی')], default='MEDIUM', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='security_se_event_t_1a00f0_idx'), models.Index(fields=['severity', 'resolved'], name='security_se_severit_d0a5b5_idx'), models.Index(fields=['user', 'timestamp'], name='security_se_user_id_6ceb62_idx')],
            },
        ),
    ]
