# Generated by Django 5.2.6 on 2025-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_alter_auditlog_user_id_securityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, choices=[('CREATE', 'ایجاد'), ('UPDATE', 'به\u200cروزرسانی'), ('DELETE', 'حذف'), ('VIEW', 'مشاهده'), ('EXPORT', 'خروجی\u200cگیری')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='patient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
