# Generated by Django 5.2.5 on 2025-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
