# Generated by Django 5.2.5 on 2025-08-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20250829_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
