# Generated by Django 5.2.5 on 2025-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_auditlog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
