# Generated by Django 5.2.5 on 2025-08-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitdm', '0002_doctorprofile_patientprofile_and_more'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitdm.patientprofile'),
        ),
    ]
