# Generated by Django 5.2.5 on 2025-08-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_initial'),
        ('gitdm', '0002_doctorprofile_patientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitdm.patientprofile'),
        ),
    ]
