# Generated by Django 5.2.5 on 2025-08-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_summarizer', '0005_add_uuid_pk'),
        ('clinical_refs', '0001_initial'),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='Clinical references automatically linked based on summary content', to='clinical_refs.clinicalreference'),
        ),
        migrations.AlterField(
            model_name='aisummary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_core.patient'),
        ),
    ]
