# Generated by Django migration creator on 2025-08-29 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.JSONField(default=dict)),
                ('assessment', models.JSONField(default=dict)),
                ('plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_core.patient')),
            ],
            options={
                'indexes': ["models.Index(fields=['patient', 'occurred_at'], name='diab_encoun_patient_6a8a0f_idx')", "models.Index(fields=['created_by', 'created_at'], name='diab_encoun_created_f7c88e_idx')"],
            },
        ),
    ]
