# Generated by Django 5.2.5 on 2025-08-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.JSONField(default=dict)),
                ('assessment', models.JSONField(default=dict)),
                ('plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_core.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'occurred_at'], name='diab_encoun_patient_0dac9d_idx'), models.Index(fields=['created_by', 'created_at'], name='diab_encoun_created_d337bf_idx')],
            },
        ),
    ]
