# Generated by Django 5.2.5 on 2025-08-28 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.JSONField(default=dict)),
                ('assessment', models.JSONField(default=dict)),
                ('plan', models.JSONField(default=dict)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_core.patient')),
            ],
        ),
    ]
