name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dotenv-linter
        run: |
          curl -sSfL https://github.com/dotenv-linter/dotenv-linter/releases/latest/download/dotenv-linter-linux-x86_64.tar.gz | tar xzf - dotenv-linter
          sudo mv dotenv-linter /usr/local/bin
      - uses: pre-commit/action@v3.0.0